### ISSUE TITLE
composer build-database command fails

### ISSUE THREAD

**Issue by geoff-maddock** [aleksblendwerk/pingcrm-symfony#1]
```
cutups@cutups-PC:~/PhpstormProjects/pingcrm-symfony$ composer build-database
> symfony console doctrine:database:create --if-not-exists

  [InvalidArgumentException]
  Command "console" is not defined.  

Script symfony console doctrine:database:create --if-not-exists handling the build-database event returned with error code 1
```

Not quite sure what the issue is.  I have a DATABASE_URL defined in .env.local

**Comment by aleksblendwerk** [comment]
Hi Geoff,

that looks odd. The `DATABASE_URL` does not seem to be the issue but the interplay of Symfony CLI and the `bin/console` script.

Does `symfony` point to the Symfony CLI on your system? As in: is the output you get when just running `symfony` in your shell similar to this?

```
$ symfony

Symfony CLI version v4.21.2 (c) 2017-2020 Symfony SAS
Symfony CLI helps developers manage projects, from local code to remote infrastructure
[...]
```

Here are instructions on how to install Symfony CLI: https://symfony.com/download

If everything else fails, you can just use the `bin/console` script without using `symfony`, like this:

```
php bin/console doctrine:database:create --if-not-exists
php bin/console doctrine:schema:drop --ansi --force --full-database --no-interaction
php bin/console doctrine:schema:update --ansi --force --no-interaction
php bin/console doctrine:fixtures:load --ansi --no-interaction
```

But then you also won't be able to run the local web server using `symfony serve` as described in the next step.

I hope this helps, let me know!

---

Also I just noticed that the `README.md` only mentions the installation of Symfony CLI in the next step, although the Composer script already assumes it is installed. I will definitely change that. Sorry for that.

**Comment by geoff-maddock** [comment]
I found the issue for me.  I had this other (older?) symfony installer in my path:
```
cutups@cutups-PC:~/PhpstormProjects/pingcrm-symfony$ symfony -V
Symfony Installer version 1.5.11
```

I don't use that, so I removed it and installed the newer one.

That worked.

I am running into another issue not related to the composer command.  When I try to serve the app:
```
cutups@cutups-PC:~/PhpstormProjects/pingcrm-symfony$ symfony serve
Tailing Web Server log file (/c/Users/cutups/.symfony/log/d2452d0263fdbd0f2e314c46de891031ed1a73b8.log)
Tailing PHP-FPM log file (/c/Users/cutups/.symfony/log/d2452d0263fdbd0f2e314c46de891031ed1a73b8/53fb8ec204547646acb3461995e4da5a54cc7575.log)

 [OK] Web server listening
      The Web server is using PHP FPM 7.4.13
      https://127.0.0.1:8000


[Web Server ] Dec  5 16:36:30 |INFO   | PHP    listening path="/usr/sbin/php-fpm7.4" php="7.4.13" port=46307
[PHP-FPM    ] Dec  5 16:36:30 |NOTICE | FPM    fpm is running, pid 1799 
[PHP-FPM    ] Dec  5 16:36:30 |NOTICE | FPM    ready to handle connections 
[PHP-FPM    ] Dec  5 16:36:30 |NOTICE | FPM    systemd monitor interval set to 10000ms)
```

I try to access the site but I get site can't be reached.   I think this is a WSL question though, outside of your project.

Thanks for the help!

**Comment by geoff-maddock** [comment]
I discovered connecting to https://localhost:8000/login worked for me.

**Comment by aleksblendwerk** [comment]
I am glad it worked out.

Thanks for reporting this, I updated the installation instructions in `README.md` a bit to make it clear that Symfony CLI must be installed.
