### ISSUE TITLE
Typo - BuildInertiaDefaultPropsTrait file

### ISSUE THREAD

**Issue by Damian972** [aleksblendwerk/pingcrm-symfony#2]
Typo on `if ($session->getFlashBag()->has('success'))`, it should be `if ($session->getFlashBag()->has('error'))` I guess.
https://github.com/aleksblendwerk/pingcrm-symfony/blob/47d09e967eb80866cdc5a45fe639339d80abcfb9/src/Controller/Traits/BuildInertiaDefaultPropsTrait.php#L31

**Comment by aleksblendwerk** [comment]
Thanks for reporting, @Damian972. I wonder why that hasn't lead to any errors yet, need to investigate further... 🙃

**Comment by aleksblendwerk** [comment]
Fixed by #7.
