### ISSUE TITLE
Vue 3 not supported

### ISSUE THREAD

**Issue by AmProsius** [aleksblendwerk/pingcrm-symfony#4]
I'd like to see the demo upgraded to Vue 3 like [inertia/pingcrm #166](https://github.com/inertiajs/pingcrm/pull/166). I'd be happy to create a PR if you're interested.

**Comment by aleksblendwerk** [comment]
Hey @AmProsius, a PR sounds nice!

And this project could definitely need a couple of updates, I just haven't been following Inertia and even Symfony that close recently, so not sure where to start. But your proposal sounds like a good start! :)

**Comment by AmProsius** [comment]
I'm sorry, but since I don't work with Symfony anymore, I won't spend time on a PR.

Wish you all the best though!
